# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 vmImage: 'ubuntu-latest' # Adjust VM image if needed
stages:
- stage: Build
 jobs:
 - job: Build_Job
 steps:
 - task: Maven@3 # Use the appropriate Maven version task
 inputs:
 mavenVersion: '3.x' # Specify your Maven version
 mavenPomFile: 'pom.xml' # Path to your pom.xml file
 goals: 'clean package' # Maven goals to execute (clean and package)
 publishMavenArtifacts: true #